spring.application.name=api-gateway
server.port=${PORT:10000}
server.address=0.0.0.0

routes.user-uri=https://${USER_HOST}
routes.expense-uri=https://${EXPENSE_HOST}
routes.sms-uri=https://${SMS_HOST}
routes.parser-uri=https://${PARSER_HOST}

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always