spring.application.name=api-gateway
server.port=8084
server.address=0.0.0.0

routes.user-uri=http://localhost:8081
routes.expense-uri=http://localhost:8080
routes.sms-uri=http://localhost:8082
routes.parser-uri=http://localhost:8083

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
